import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/banner";
import Card from "../components/card/card";
import SectionCards from "../components/card/section-cards";
import NavBar from "../components/navBar/navbar";
import { getPopularVideos, getVideos } from "../lib/video";
import { startFetchMyQuery } from "../db/hasura";
import classes from "../styles/Home.module.css";

export async function getServerSideProps() {
	const disneyVideos = await getVideos("disney trailer");
	const MarvelVideos = await getVideos("marvel trailer");
	const travelVideos = await getVideos("travel");
	const popularVideos = await getPopularVideos();
	return {
		props: { disneyVideos, MarvelVideos, travelVideos, popularVideos },
	};
}
export default function Home({
	disneyVideos,
	MarvelVideos,
	travelVideos,
	popularVideos,
}) {
	startFetchMyQuery();
	return (
		<main className={classes.mainPage}>
			<div className={classes.container}>
				<Head>
					<title>Netflix</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<NavBar />
				<Banner
					videoId="4zH5iYM4wJo"
					title={"Clifford the red dog"}
					subTitle="a very cute dog"
					imgUrl="/static/clifford.webp"
				/>
				<div className={classes.sectionWrapper}>
					<SectionCards
						title={"Disney"}
						videos={disneyVideos}
						size={"large"}
					/>
					<SectionCards
						title={"Travel"}
						videos={travelVideos}
						size={"small"}
					/>
					<SectionCards
						title={"Marvel"}
						videos={MarvelVideos}
						size={"medium"}
					/>
					<SectionCards
						title={"Popular"}
						videos={popularVideos}
						size={"small"}
					/>
				</div>
			</div>
		</main>
	);
}
